name: 'Supported legacy versions'
description: 'Get the backend versions the app will run on except the latest one'
inputs:
    instance-url-latest:
        description: 'The URL to the instance witht the latest version. Required if maxDHIS2Version is not specified in d2.config'
        required: false
    username:
        description: 'The DHIS2 username for authentication. Required if maxDHIS2Version is not specified in d2.config'
        required: false
    password:
        description: 'The DHIS2 password for authentication. Required if maxDHIS2Version is not specified in d2.config'
        required: false
outputs:
    versions:
        description: 'An array containing the supported legacy versions'
runs:
    using: 'composite'
    steps:
        - run: echo "HER $GITHUB_WORKSPACE"
          shell: bash
        - uses: ./.github/actions/precheck-max
          id: precheck
          with:
              workspace: ${{ env.$GITHUB_WORKSPACE }}

        - if: steps.precheck.outputs.max-version != ''
          uses: dhis2/action-instance-version@v1
          id: instance-version-latest
          with:
              instance-url: ${{ inputs.instance-url-latest }}
              username: ${{ inputs.username }}
              password: ${{ inputs.password }}

        - uses: ./.github/actions/legacy-versions
          with:
              latest-version: ${{ steps.precheck.outputs.max-version || (steps.instance-version-latest.outputs && steps.instance-version-latest.outputs.version) }}
