on: [push]

jobs:
    get-legacy-versions:
        runs-on: ubuntu-latest
        outputs:
            versions: ${{ steps.legacy-versions.outputs.versions }}
        steps:
            - uses: actions/checkout@v2

            - uses: ./
              id: legacy-versions
              with:
                  instance-url-latest: https://test.e2e.dhis2.org/dev
                  username: system
                  password: System123

            - name: verify
              run: if [ $versions != '["2.38","2.39"]' ]; then exit 1; fi;
              env:
                  versions: ${{ steps.legacy-versions.outputs.versions }}
